import { CircleDollarSign, ReceiptText, TrendingUp, Users } from "lucide-react";
import { StatCard } from "@/components/stat-card";
import { prisma } from "@/lib/prisma";
import { formatMoney } from "@/lib/utils";
export const dynamic = "force-dynamic";

export default async function ReportsPage(){
  const [settings,patients,visits,payments,expenses]=await Promise.all([
    prisma.clinicSettings.findUnique({where:{id:"clinic"}}), prisma.patient.count({where:{isArchived:false}}),
    prisma.visit.findMany({select:{costCents:true,status:true,date:true}}), prisma.payment.findMany({where:{deletedAt:null},select:{amountCents:true,paidAt:true}}),
    prisma.expense.findMany({where:{deletedAt:null},select:{amountCents:true,date:true,categoryId:true,category:{select:{name:true}}}})
  ]); const currency=settings?.currency||"SYP"; const income=payments.reduce((s,x)=>s+x.amountCents,0); const expenseTotal=expenses.reduce((s,x)=>s+x.amountCents,0); const treatmentValue=visits.reduce((s,x)=>s+x.costCents,0); const receivables=Math.max(0,treatmentValue-income); const map=new Map<string,number>(); expenses.forEach(e=>{const k=e.category?.name||"غير مصنف";map.set(k,(map.get(k)||0)+e.amountCents)}); const cats=[...map.entries()].sort((a,b)=>b[1]-a[1]); const max=Math.max(...cats.map(x=>x[1]),1);
  return <><div className="page-header"><div><h1>التقارير المالية والتشغيلية</h1><p>ملخص مباشر للإيرادات والمصروفات والمستحقات.</p></div><span className="badge muted">يمكن طباعة الصفحة من المتصفح</span></div><section className="grid stats-grid"><StatCard label="عدد المرضى" value={patients} icon={Users}/><StatCard label="إجمالي الإيرادات" value={formatMoney(income,currency)} icon={CircleDollarSign}/><StatCard label="إجمالي المصروفات" value={formatMoney(expenseTotal,currency)} icon={ReceiptText}/><StatCard label="صافي الربح" value={formatMoney(income-expenseTotal,currency)} icon={TrendingUp}/></section><section className="grid two-cols"><div className="card"><div className="card-title"><div><h3>القيمة العلاجية والتحصيل</h3><p>مقارنة الجلسات بالمبالغ المقبوضة</p></div></div><div className="details-list"><div className="detail"><small>قيمة الجلسات</small><strong>{formatMoney(treatmentValue,currency)}</strong></div><div className="detail"><small>المبالغ المحصلة</small><strong style={{color:"#047857"}}>{formatMoney(income,currency)}</strong></div><div className="detail"><small>المبالغ المستحقة</small><strong style={{color:"#be123c"}}>{formatMoney(receivables,currency)}</strong></div><div className="detail"><small>الجلسات المكتملة</small><strong>{visits.filter(v=>v.status==="COMPLETED").length}</strong></div></div></div><div className="card"><div className="card-title"><div><h3>المصروفات حسب التصنيف</h3><p>التصنيفات الأعلى تكلفة</p></div></div>{cats.length?<div className="bar-chart">{cats.map(([label,value])=><div className="bar-row" key={label}><span>{label}</span><div className="bar-track"><div className="bar-fill" style={{width:`${value/max*100}%`}}/></div><strong>{formatMoney(value,currency)}</strong></div>)}</div>:<div className="empty"><strong>لا توجد مصروفات</strong></div>}</div></section></>;
}
