import Link from "next/link";
import { notFound } from "next/navigation";
import { Archive, CalendarPlus, CircleDollarSign, Phone, Plus, Stethoscope } from "lucide-react";
import { archivePatientAction, createAppointmentAction, createPaymentAction, createVisitAction } from "@/app/actions";
import { FlashMessage } from "@/components/flash-message";
import { StatusBadge } from "@/components/status-badge";
import { SubmitButton } from "@/components/submit-button";
import { genderLabels, paymentMethodLabels } from "@/lib/constants";
import { prisma } from "@/lib/prisma";
import { ageFromBirthDate, formatDate, formatDateTime, formatMoney, inputDateTime } from "@/lib/utils";

export const dynamic = "force-dynamic";

export default async function PatientDetailsPage({ params, searchParams }: { params: Promise<{ id:string }>; searchParams: Promise<{ error?:string; success?:string }> }) {
  const { id }=await params; const { error,success }=await searchParams;
  const [patient,settings]=await Promise.all([
    prisma.patient.findUnique({where:{id},include:{medicalHistory:true,visits:{orderBy:{date:"desc"}},payments:{where:{deletedAt:null},orderBy:{paidAt:"desc"}},appointments:{orderBy:{startAt:"desc"}},treatmentPlans:true}}),
    prisma.clinicSettings.findUnique({where:{id:"clinic"}})
  ]);
  if(!patient||patient.isArchived) notFound();
  const currency=settings?.currency||"SYP"; const totalCost=patient.visits.reduce((s,v)=>s+v.costCents,0)+patient.treatmentPlans.reduce((s,p)=>s+p.costCents,0); const totalPaid=patient.payments.reduce((s,p)=>s+p.amountCents,0); const remaining=Math.max(0,totalCost-totalPaid); const age=ageFromBirthDate(patient.birthDate);
  const nextAppointment=patient.appointments.filter(a=>a.startAt>=new Date()&&["PENDING","CONFIRMED"].includes(a.status)).sort((a,b)=>a.startAt.getTime()-b.startAt.getTime())[0];
  return <><FlashMessage error={error} success={success}/><section className="profile-hero"><div className="profile-main">{patient.photoDataUrl?<img className="patient-photo large" src={patient.photoDataUrl} alt=""/>:<div className="patient-photo large">{patient.fullName.slice(0,1)}</div>}<div><h1>{patient.fullName}</h1><div className="profile-meta"><span>{patient.fileNumber}</span><span><Phone size={13} style={{display:"inline"}}/> {patient.phone}</span><span>{genderLabels[patient.gender]}{age!==null?`، ${age} سنة`:""}</span><span>الموعد القادم: {formatDateTime(nextAppointment?.startAt)}</span></div></div></div><div className="money-summary"><div className="money-box"><small>التكلفة الإجمالية</small><strong>{formatMoney(totalCost,currency)}</strong></div><div className="money-box"><small>المدفوع</small><strong style={{color:"#047857"}}>{formatMoney(totalPaid,currency)}</strong></div><div className="money-box"><small>المتبقي</small><strong style={{color:"#be123c"}}>{formatMoney(remaining,currency)}</strong></div></div></section>
  <section className="grid two-cols"><div className="card"><div className="card-title"><div><h3>بيانات المريض</h3><p>المعلومات الشخصية والطبية</p></div></div><div className="details-list"><div className="detail"><small>الهاتف البديل</small>{patient.alternativePhone||"—"}</div><div className="detail"><small>البريد</small>{patient.email||"—"}</div><div className="detail"><small>العنوان</small>{[patient.city,patient.address].filter(Boolean).join("، ")||"—"}</div><div className="detail"><small>المهنة</small>{patient.occupation||"—"}</div><div className="detail"><small>فصيلة الدم</small>{patient.medicalHistory?.bloodType||"—"}</div><div className="detail"><small>الحساسيات</small>{patient.medicalHistory?.allergies||"لا توجد معلومات"}</div><div className="detail"><small>الأمراض المزمنة</small>{patient.medicalHistory?.chronicDiseases||"لا توجد معلومات"}</div><div className="detail"><small>الأدوية</small>{patient.medicalHistory?.medications||"لا توجد معلومات"}</div></div><hr className="section-divider"/><form action={archivePatientAction}><input name="id" type="hidden" value={patient.id}/><button className="btn btn-danger btn-small" type="submit"><Archive size={15}/> أرشفة الملف</button></form></div>
  <div className="card"><div className="card-title"><div><h3>إضافة جلسة علاج</h3><p>التكلفة تُضاف لحساب المريض.</p></div><Stethoscope size={20}/></div><form action={createVisitAction}><input name="patientId" type="hidden" value={patient.id}/><div className="form-grid"><div className="field"><label>تاريخ الجلسة</label><input className="input" name="date" type="datetime-local" defaultValue={inputDateTime()}/></div><div className="field"><label>نوع الجلسة *</label><input className="input" name="type" required placeholder="حشوة، تنظيف، علاج عصب"/></div><div className="field"><label>الأسنان</label><input className="input" name="teeth" placeholder="11، 12، 26"/></div><div className="field"><label>الحالة</label><select className="select" name="status"><option value="COMPLETED">مكتملة</option><option value="UPCOMING">قادمة</option><option value="CANCELLED">ملغاة</option><option value="NO_SHOW">لم يحضر</option></select></div><div className="field"><label>التشخيص</label><textarea className="textarea" name="diagnosis"/></div><div className="field"><label>الإجراء المنفذ</label><textarea className="textarea" name="procedure"/></div><div className="field"><label>التكلفة</label><input className="input" min="0" step="0.01" name="cost" type="number"/></div><div className="field"><label>موعد المتابعة</label><input className="input" name="nextFollowUp" type="datetime-local"/></div><div className="field full"><label>ملاحظات الطبيب</label><textarea className="textarea" name="doctorNotes"/></div></div><div style={{marginTop:13}}><SubmitButton><Plus size={16}/> إضافة الجلسة</SubmitButton></div></form></div></section>
  <section className="grid two-cols" style={{marginTop:18}}><div className="card"><div className="card-title"><div><h3>تسجيل دفعة</h3><p>إنشاء سند قبض جديد.</p></div><CircleDollarSign size={20}/></div><form action={createPaymentAction}><input name="patientId" type="hidden" value={patient.id}/><div className="form-grid"><div className="field"><label>قيمة الدفعة *</label><input className="input" min="0.01" step="0.01" name="amount" type="number" required/></div><div className="field"><label>تاريخ الدفع</label><input className="input" name="paidAt" type="datetime-local" defaultValue={inputDateTime()}/></div><div className="field"><label>طريقة الدفع</label><select className="select" name="method"><option value="CASH">نقدي</option><option value="CARD">بطاقة</option><option value="BANK_TRANSFER">تحويل بنكي</option><option value="OTHER">أخرى</option></select></div><div className="field"><label>المستلم</label><input className="input" name="receiver" defaultValue="إدارة العيادة"/></div><div className="field full"><label>ملاحظات</label><textarea className="textarea" name="notes"/></div></div><div style={{marginTop:13}}><SubmitButton>حفظ الدفعة</SubmitButton></div></form></div>
  <div className="card"><div className="card-title"><div><h3>إضافة موعد</h3><p>منع تلقائي لتداخل المواعيد.</p></div><CalendarPlus size={20}/></div><form action={createAppointmentAction}><input name="patientId" type="hidden" value={patient.id}/><input name="returnTo" type="hidden" value={`/patients/${patient.id}`}/><div className="form-grid"><div className="field"><label>التاريخ والوقت *</label><input className="input" name="startAt" type="datetime-local" required/></div><div className="field"><label>المدة بالدقائق</label><input className="input" name="duration" type="number" defaultValue={settings?.defaultAppointmentMins||30} min="10"/></div><div className="field"><label>نوع الموعد *</label><input className="input" name="type" required/></div><div className="field"><label>الحالة</label><select className="select" name="status"><option value="PENDING">بانتظار التأكيد</option><option value="CONFIRMED">مؤكد</option></select></div><div className="field full"><label>ملاحظات</label><textarea className="textarea" name="notes"/></div></div><div style={{marginTop:13}}><SubmitButton>حفظ الموعد</SubmitButton></div></form></div></section>
  <section className="grid two-cols" style={{marginTop:18}}><div className="card"><div className="card-title"><div><h3>سجل الجلسات</h3><p>{patient.visits.length} جلسة</p></div></div>{patient.visits.length?<div className="timeline">{patient.visits.map(v=><div className="timeline-item" key={v.id}><div style={{display:"flex",justifyContent:"space-between",gap:10}}><h4>الجلسة {v.sessionNumber}: {v.type}</h4><StatusBadge status={v.status}/></div><p>{formatDateTime(v.date)} — الأسنان: {v.teeth||"غير محدد"}</p><p>{v.diagnosis||v.procedure||"لا توجد تفاصيل"}</p><p><strong>التكلفة: {formatMoney(v.costCents,currency)}</strong></p></div>)}</div>:<div className="empty"><strong>لا توجد جلسات</strong></div>}</div>
  <div className="card"><div className="card-title"><div><h3>سجل الدفعات</h3><p>{patient.payments.length} دفعة</p></div></div>{patient.payments.length?<div className="table-wrap"><table className="table"><thead><tr><th>السند</th><th>التاريخ</th><th>الطريقة</th><th>المبلغ</th></tr></thead><tbody>{patient.payments.map(p=><tr key={p.id}><td>{p.receiptNumber}</td><td>{formatDate(p.paidAt)}</td><td>{paymentMethodLabels[p.method]}</td><td><strong style={{color:"#047857"}}>{formatMoney(p.amountCents,currency)}</strong></td></tr>)}</tbody></table></div>:<div className="empty"><strong>لا توجد دفعات</strong></div>}</div></section><div style={{marginTop:18}}><Link className="btn btn-ghost" href="/patients">العودة إلى المرضى</Link></div></>;
}
