import { KeyRound, Save, Settings } from "lucide-react";
import { changePasswordAction, updateSettingsAction } from "@/app/actions";
import { FlashMessage } from "@/components/flash-message";
import { SubmitButton } from "@/components/submit-button";
import { requireUser } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
export const dynamic = "force-dynamic";

export default async function SettingsPage({searchParams}:{searchParams:Promise<{error?:string;success?:string}>}){
  const {error,success}=await searchParams; const session=await requireUser(); const settings=await prisma.clinicSettings.findUnique({where:{id:"clinic"}});
  return <><div className="page-header"><div><h1>إعدادات العيادة</h1><p>الهوية العامة، العملة، المواعيد وأمان الحساب.</p></div></div><FlashMessage error={error} success={success}/><section className="grid two-cols"><div className="card"><div className="card-title"><div><h3>بيانات العيادة</h3><p>تظهر في رأس لوحة الإدارة.</p></div><Settings size={20}/></div><form action={updateSettingsAction}><div className="form-grid"><div className="field"><label>اسم العيادة</label><input className="input" name="clinicName" defaultValue={settings?.clinicName} required/></div><div className="field"><label>اسم الطبيب</label><input className="input" name="doctorName" defaultValue={settings?.doctorName} required/></div><div className="field"><label>الهاتف</label><input className="input" name="phone" defaultValue={settings?.phone||""}/></div><div className="field"><label>البريد</label><input className="input" name="email" type="email" defaultValue={settings?.email||""}/></div><div className="field full"><label>العنوان</label><input className="input" name="address" defaultValue={settings?.address||""}/></div><div className="field"><label>العملة</label><select className="select" name="currency" defaultValue={settings?.currency||"SYP"}><option value="SYP">ليرة سورية SYP</option><option value="USD">دولار USD</option><option value="SAR">ريال سعودي SAR</option><option value="EUR">يورو EUR</option><option value="JOD">دينار أردني JOD</option></select></div><div className="field"><label>مدة الموعد</label><input className="input" name="defaultAppointmentMins" type="number" min="10" defaultValue={settings?.defaultAppointmentMins||30}/></div><div className="field full"><label>أوقات العمل</label><input className="input" name="workingHours" defaultValue={settings?.workingHours||""}/></div></div><div style={{marginTop:13}}><SubmitButton><Save size={16}/> حفظ الإعدادات</SubmitButton></div></form></div><div className="card"><div className="card-title"><div><h3>تغيير كلمة المرور</h3><p>الحساب الحالي: {session.email}</p></div><KeyRound size={20}/></div><form action={changePasswordAction}><div className="field" style={{marginBottom:13}}><label>كلمة المرور الحالية</label><input className="input" name="currentPassword" type="password" required/></div><div className="field"><label>كلمة المرور الجديدة</label><input className="input" name="newPassword" type="password" minLength={8} required/></div><div style={{marginTop:13}}><SubmitButton>تغيير كلمة المرور</SubmitButton></div></form><hr className="section-divider"/><div className="alert error" style={{marginBottom:0}}>بعد أول دخول، غيّري كلمة المرور الافتراضية مباشرة، ولا تضعي بيانات الدخول داخل GitHub.</div></div></section></>;
}
