import Link from "next/link";
import { ArrowRight, Save, UserPlus } from "lucide-react";
import { createPatientAction } from "@/app/actions";
import { FlashMessage } from "@/components/flash-message";
import { SubmitButton } from "@/components/submit-button";

export const dynamic = "force-dynamic";

export default async function NewPatientPage({ searchParams }: { searchParams: Promise<{ error?: string }> }) {
  const { error } = await searchParams;
  return <><div className="page-header"><div><h1>إضافة مريض جديد</h1><p>إنشاء ملف طبي ومالي كامل للمريض.</p></div><Link className="btn btn-ghost" href="/patients"><ArrowRight size={17}/> رجوع</Link></div><FlashMessage error={error}/><form action={createPatientAction} encType="multipart/form-data"><div className="card"><div className="card-title"><div><h3>البيانات الشخصية</h3><p>الحقول الأساسية مطلوبة لإنشاء الملف.</p></div><UserPlus size={20}/></div><div className="form-grid">
    <div className="field"><label>رقم الملف</label><input className="input" name="fileNumber" placeholder="يُنشأ تلقائيًا"/></div><div className="field"><label>صورة المريض</label><input className="input" name="photo" type="file" accept="image/*"/></div>
    <div className="field"><label>الاسم الأول *</label><input className="input" name="firstName" required/></div><div className="field"><label>اسم الأب</label><input className="input" name="fatherName"/></div><div className="field"><label>اسم العائلة *</label><input className="input" name="lastName" required/></div>
    <div className="field"><label>الجنس *</label><select className="select" name="gender"><option value="MALE">ذكر</option><option value="FEMALE">أنثى</option><option value="OTHER">آخر</option></select></div><div className="field"><label>تاريخ الميلاد</label><input className="input" name="birthDate" type="date"/></div><div className="field"><label>رقم الهاتف *</label><input className="input" name="phone" required/></div>
    <div className="field"><label>هاتف بديل</label><input className="input" name="alternativePhone"/></div><div className="field"><label>البريد الإلكتروني</label><input className="input" name="email" type="email"/></div><div className="field"><label>المدينة</label><input className="input" name="city"/></div><div className="field"><label>المهنة</label><input className="input" name="occupation"/></div><div className="field"><label>الحالة الاجتماعية</label><input className="input" name="maritalStatus"/></div><div className="field full"><label>العنوان</label><input className="input" name="address"/></div>
    <div className="field"><label>اسم شخص للطوارئ</label><input className="input" name="emergencyContactName"/></div><div className="field"><label>هاتف الطوارئ</label><input className="input" name="emergencyContactPhone"/></div><div className="field"><label>صلة القرابة</label><input className="input" name="emergencyRelation"/></div><div className="field full"><label>ملاحظات عامة</label><textarea className="textarea" name="notes"/></div>
  </div></div><div className="card" style={{marginTop:18}}><div className="card-title"><div><h3>التاريخ الطبي</h3><p>معلومات تساعد الطبيب قبل العلاج.</p></div></div><div className="form-grid"><div className="field"><label>فصيلة الدم</label><input className="input" name="bloodType"/></div><div className="field"><label>الأمراض المزمنة</label><textarea className="textarea" name="chronicDiseases"/></div><div className="field"><label>الحساسيات</label><textarea className="textarea" name="allergies"/></div><div className="field"><label>الأدوية الحالية</label><textarea className="textarea" name="medications"/></div><div className="field full"><label>العمليات السابقة</label><textarea className="textarea" name="previousSurgeries"/></div><div className="full check-grid"><label className="check-item"><input name="pregnant" type="checkbox"/> حمل</label><label className="check-item"><input name="smoking" type="checkbox"/> تدخين</label><label className="check-item"><input name="hypertension" type="checkbox"/> ضغط دم</label><label className="check-item"><input name="diabetes" type="checkbox"/> سكري</label><label className="check-item"><input name="heartDisease" type="checkbox"/> أمراض قلب</label><label className="check-item"><input name="bleedingDisorder" type="checkbox"/> اضطراب نزيف</label></div><div className="field full"><label>ملاحظات طبية</label><textarea className="textarea" name="medicalNotes"/></div></div></div><div style={{display:"flex",justifyContent:"flex-end",marginTop:18}}><SubmitButton><Save size={17}/> حفظ ملف المريض</SubmitButton></div></form></>;
}
